# Generated by Django 2.2.4 on 2019-08-14 22:45

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('script_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.TextField()),
                ('output', models.IntegerField()),
                ('file_path', models.CharField(max_length=512)),
            ],
        ),
    ]
