# Generated by Django 2.2.4 on 2019-08-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0002_auto_20190814_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='project',
            field=models.CharField(default='demo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='script',
            name='script_id',
            field=models.IntegerField(null=True),
        ),
    ]
