# Generated by Django 2.2.4 on 2019-08-18 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0003_auto_20190817_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='script_id',
        ),
    ]
