# Generated by Django 2.2.4 on 2019-08-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0004_remove_script_script_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='_id',
        ),
        migrations.AddField(
            model_name='script',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
