# Generated by Django 2.2.4 on 2019-08-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('script_repo', models.CharField(max_length=250)),
                ('dataset_repo', models.CharField(max_length=250)),
            ],
        ),
    ]
